apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
  name: argocd-server
spec:
  rules:
    - host: argocd.int.babyvelociraptor.com
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server
              servicePort: 80
  tls:
    - hosts:
      - argocd.int.babyvelociraptor.com
      secretName: tls-secret
    