apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: ingress-nginx

# configMapGenerator:
#   - name: nginx-configuration
#     behavior: merge
#     literals:
#       - proxy-read-timeout=300s
#       - proxy-send-timeout=300s

images:
  - name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    newName: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: nginx-ingress-controller
      namespace: ingress-nginx
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http-port=8080
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --https-port=8443
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --ingress-class=ingress-nginx
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/ports/1/containerPort
        value: 8443
  - target:
      version: v1
      kind: Service
      name: ingress-nginx
      namespace: ingress-nginx
    patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.1.240

resources:
  - ../base