apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.int.babyvelociraptor.com.
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240