apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: ingress-nginx

# configMapGenerator:
#   - name: nginx-configuration
#     behavior: merge
#     literals:
#       - proxy-read-timeout=300s
#       - proxy-send-timeout=300s

namespace: ingress-nginx

replicas:
  - name: nginx-ingress-controller
    count: 2

#Pulled the installers from nginx-0.30.0 tag on ingress-nginx project
resources:
  - ./mandatory.yaml
  - ./cloud-generic.yaml