apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: ingress-nginx

# configMapGenerator:
#   - name: nginx-configuration
#     behavior: merge
#     literals:
#       - proxy-read-timeout=300s
#       - proxy-send-timeout=300s

namespace: ingress-nginx

replicas:
  - name: nginx-ingress-controller
    count: 2

resources:
  - https://github.com/kubernetes/ingress-nginx/blob/nginx-0.30.0/deploy/static/mandatory.yaml
  - https://github.com/kubernetes/ingress-nginx/blob/nginx-0.30.0/deploy/static/provider/cloud-generic.yaml