apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - clusterissuer.yaml

images:
  - name: quay.io/jetstack/cert-manager-cainjector
    newName: quay.io/jetstack/cert-manager-cainjector-arm
  - name: quay.io/jetstack/cert-manager-controller
    newName: quay.io/jetstack/cert-manager-controller-arm
  - name: quay.io/jetstack/cert-manager-webhook
    newName: quay.io/jetstack/cert-manager-webhook-arm